### ISSUE TITLE
Cannot work with shinyapps.io

### ISSUE THREAD

**Issue by csliangy** [Appsilon/shiny.router#56]
Working perfectly in my local environment, however, the application URL will be stripped out.

For example,  the initial FULL URL on shinyapps.io:
https://my_org.shinyapps.io/my_application_name_on_shinyapps.io/

Once I click one link to another page, it becomes: 
https://my_org.shinyapps.io/#!/explore-indicators

The "**my_application_name_on_shinyapps.io**" is gone!!!

**Comment by csliangy** [comment]
Also verified the sample application on shinyapps.io, the same issue.

**Comment by krystian8207** [comment]
It's already fixed with #57
