### ISSUE TITLE
Rendering slider_input from server with renderUI forces whole UI to completely redraw when routing page

### ISSUE THREAD

**Issue by FractalPolarity** [Appsilon/shiny.router#65]
Looks like the problem is present with shiny.semantic slider_input as well as standard shiny sliderInput.

`server <- shinyServer(function(input, output) {`<br>`router(input, output)
  slider_ui <- sliderInput("slider", "slider_label", 0 , 10 , 3, 1, 3)`<br>`
  output$slider <- renderUI(slider_ui)`<br>`
}
` 
Above makes whole ui refresh on routing ( even elements outside `router_ui()` )

I've checked some additional components (numericInput, semantic date_input, actionButton) and it is working fine with them.

**Comment by krystian8207** [comment]
@dokato this should be fixed as well

**Comment by dokato** [comment]
Yeap, this looks fine.
