### ISSUE TITLE
Add an options to reset page objects

### ISSUE THREAD

**Issue by krystian8207** [Appsilon/shiny.router#70]
The list of objects:
- reactive values (see: https://appsilon.com/how-to-safely-remove-a-dynamic-shiny-module/)
- output values (`output$name <- NULL` see #69)
- observers (see: https://appsilon.com/how-to-safely-remove-a-dynamic-shiny-module/)

**Comment by dokato** [comment]
@krystian8207 is this completed?

**Comment by krystian8207** [comment]
Yes, the current implementation doesn't require this feature anymore.
