### ISSUE TITLE
Using shiny.router to receive POST requests on specific routes

### ISSUE THREAD

**Issue by aljrico** [Appsilon/shiny.router#81]
Is it possible to set up a webhook so we can receive POST requests to specific routes?

So let's say that I have a shiny app deployed on https://itsme.shinyapps.io/myapp

I want to set up a webhook so the app 'wakes up' and the server does 'something' if a user sends a POST request with a json file to - let's say - https://itsme.shinyapps.io/myapp/myfeature

How would be the recommended way of addressing this with `shiny.router`? Is it even possible?

Thank you! (I'm aware the question is a bit vague, let me know if you need more clarification)

**Comment by marekrogala** [comment]
Hi @aljrico, thanks for the question! shiny.router does not handling POST requests at the moment.
