### ISSUE TITLE
shiny.router not working on RSConnect server

### ISSUE THREAD

**Issue by u9090** [Appsilon/shiny.router#83]
It seems that `shiny.router` package does not work when an app is deployed on RSConnect.
Using the code provided in the [example `semanticui` app](https://github.com/Appsilon/shiny.router/blob/master/examples/semanticui/app.R), the URL of the pages remain the same.

Any workaround maybe?

**Comment by rszymanski** [comment]
Hi @u9090, thank you for using the `shiny.router` package and submitting the issue.

I have deployed the referred example app to RStudio Connect and it is working on my side. Please let me know which URL route you are using in RStudio Connect. As you can view the shiny application in two ways:

* using the `apps` route: `<YOUR_RSTUDIO_CONNECT_INSTANCE_BASE_URL>/connect/apps/<APP_ID>`
* using the `content` route: `<YOUR_RSTUDIO_CONNECT_INSTANCE_BASE_URL>/connect/content/<APP_ID>`

The `apps` route is an administrative view (where you can manage access, variable settings of the deployed content etc.). In this view the shiny app is shown in an iframe. Therefore, the URL changes triggered by `shiny.router` are not reflected in the parent window URL.

When viewing the app using the `content` route, the shiny app **is not embedded** in an iframe and route changes are reflected in the window URL.

Please, let me know if that helps and whether the URL gets update when you view your app using the `content` route! :)

**Comment by u9090** [comment]
Hi @rszymanski,

Thank you for your help !
It works indeed when using the `content` route. I was not aware of the differences between the two.
