### ISSUE TITLE
multiple_radio position inline not working

### ISSUE THREAD

**Issue by u9090** [Appsilon/shiny.router#85]
Hi,

It seems that the argument 'position' of the `multiple_radio` function does not have any effect when set to 'inline'.

Using the example provided in the package manual:
```r
if (interactive()) {
  # Checkbox
  library(shiny)
  library(shiny.semantic)

  ui <- function() {
      shinyUI(
        semanticPage(
          title = "Checkbox example",
          h1("Radioboxes"),
          multiple_radio("radioboxes", "Select Letter", LETTERS[1:6], value = "A", position = "inline"),
          p("Selected letter:"),
          textOutput("selected_letter")
       )
     )
  }

  server <- shinyServer(function(input, output) {
     output$selected_letter <- renderText(input$radioboxes)
  })

  shinyApp(ui = ui(), server = server)
}
```

**Comment by rszymanski** [comment]
Hi @u9090, thank you for using the `shiny.semantic` package. The issue you are describing seems to be related to `shiny.semantic` not `shiny.router`.

Could you please recreate the issue in the `shiny.semantic` repository here: https://github.com/Appsilon/shiny.semantic/issues?
