### ISSUE TITLE
semantic_DT: selected rows are not highlghted

### ISSUE THREAD

**Issue by u9090** [Appsilon/shiny.router#86]
When clicking on a row, it is not highlighted.

```r
if (interactive()){
    library(shiny)
    library(shiny.semantic)
    
    ui <- semanticPage(
        semantic_DTOutput("table"),
        verbatimTextOutput("DT_selection")
    )
    server <- function(input, output, session) {
        output$table <- DT::renderDataTable(
            semantic_DT(iris)
        )
        
        output$DT_selection <- renderPrint({
            print(input$table_rows_selected)
        })
    }
    shinyApp(ui, server)
}
```

Also, when trying to change the table style (e.g. by adding `style = 'default'`) , an error message appears.
`Error: formal argument "style" matched by multiple actual arguments`

**Comment by rszymanski** [comment]
Hi @u9090, thank you for using the `shiny.semantic` package. The issue you are describing seems to be related to `shiny.semantic` not `shiny.router`.

Could you please recreate the issue in the `shiny.semantic` repository here: https://github.com/Appsilon/shiny.semantic/issues?
